<?xml version="1.0" encoding="UTF-8"?>
<testsuites><testsuite name="The test suite generated by Stagehand_TestRunner" tests="1" assertions="0" failures="0" errors="1" time="0.00103688240051"><testsuite name="Stagehand_TestRunner_SimpleTestErrorTest" tests="1" assertions="0" failures="0" errors="1" time="0.00103688240051" file="/home/matsu/GITWORK/stagehand-testrunner/examples/Stagehand/TestRunner/SimpleTestErrorTest.php"><testcase name="testIsError" class="Stagehand_TestRunner_SimpleTestErrorTest" file="/home/matsu/GITWORK/stagehand-testrunner/examples/Stagehand/TestRunner/SimpleTestErrorTest.php" line="80" assertions="0" time="0.00103688240051"><error>Exception: This is an exception message.

/home/matsu/GITWORK/stagehand-testrunner/src/Stagehand/TestRunner/Runner/SimpleTestRunner/JUnitXMLReporter.php:264
/usr/share/php/simpletest/scorer.php:572
/usr/share/php/simpletest/scorer.php:811
/usr/share/php/simpletest/test_case.php:286
/usr/share/php/simpletest/exceptions.php:47
/usr/share/php/simpletest/test_case.php:143
/usr/share/php/simpletest/test_case.php:598
/home/matsu/GITWORK/stagehand-testrunner/src/Stagehand/TestRunner/Runner/SimpleTestRunner.php:130
/home/matsu/GITWORK/stagehand-testrunner/src/Stagehand/TestRunner.php:390
/home/matsu/GITWORK/stagehand-testrunner/src/Stagehand/TestRunner.php:186
/usr/share/php/src/Stagehand/CLIController.php:101
/tmp/com.piece_framework.makegood.launch/simpletestrunner:48
</error></testcase></testsuite></testsuite></testsuites>
